[tox]
envlist = lint, unit, integration
skip_missing_interpreters = true
isolated_build = true

[testenv:lint]
description = Lint with ruff + pyright + codespell
skip_install = true
deps =
    -e .[lint]
commands =
    ruff check --output-format=github {posargs}
    ruff format --check {posargs}
    codespell

[testenv:unit]
description = Run unit tests with coverage
deps =
    -e .[unit]
commands =
    coverage run --source=src -m pytest {posargs:tests/unit -v}
    coverage report

[testenv:integration]
description = Run jubilant integration tests (requires a k8s Juju controller)
deps =
    -e .[integration]
passenv =
    JUJU_*
    HOME
commands =
    pytest {posargs:tests/integration -v}
